kafka.bootstrap.servers=kafka:9092

mp.messaging.incoming.kafkatest-in.connector=smallrye-kafka
mp.messaging.incoming.kafkatest-in.topic=kafkatest
mp.messaging.incoming.kafkatest-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.kafkatest-in.group.id=websocket-consumer

quarkus.http.port=8080
quarkus.http.host=0.0.0.0