# Datasource
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/postgres

# Hibernate ORM
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true

# Optional: SQL beim Start ausführen (z.B. import.sql)
#quarkus.hibernate-orm.sql-load-script=import.sql

# HTTP
quarkus.http.port=8080
quarkus.http.host=0.0.0.0

# Kafka
kafka.bootstrap.servers=kafka:9092

mp.messaging.outgoing.kafkatest-out.connector=smallrye-kafka
mp.messaging.outgoing.kafkatest-out.topic=kafkatest
mp.messaging.outgoing.kafkatest-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer