quarkus.http.port=8080
quarkus.http.host=0.0.0.0

quarkus.datasource.db-kind=other
quarkus.datasource.jdbc.driver=org.sqlite.JDBC
quarkus.datasource.jdbc.url=jdbc:sqlite:/deployments/data/book.db
quarkus.datasource.jdbc.min-size=1
quarkus.datasource.jdbc.max-size=1

quarkus.hibernate-orm.dialect=org.hibernate.community.dialect.SQLiteDialect
quarkus.hibernate-orm.database.generation=update

quarkus.rest-client.author-client.url=http://quarkus-author-crud:8080

%dev.quarkus.datasource.jdbc.url=jdbc:sqlite:target/book-dev.db
%test.quarkus.datasource.jdbc.url=jdbc:sqlite:target/book-test.db
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.rest-client.author-client.url=http://localhost:8081
